<a href="https://colab.research.google.com/github/20130236/ML/blob/main/Lab1_20130236_L%C3%AA_%C4%90%C3%ACnh_Qu%E1%BB%91c_D%C5%A9ng.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

task 1.1:
 Develop a Python program to perform the following tasks:
– Input an integer number n.

*   Input n integer numbers x1, x2,..., xn and append them into a list L.
*   Find the max/min element in L.
*   Compute the sum of elements in L.
*   Sort the list L in ascending order.
*   Show how many positive and negative numbers are in the list L.


In [13]:
import numpy as np
n = int(input("n="))
arr = []
for i in range(n):
    arr.append(int(input("number =")))

print(arr)
maxNum = np.max(arr)
print("max = " + str(maxNum))
minNum = np.min(arr)
print("min = " + str(minNum))
sumNum = np.sum(arr)
print("sum = " + str(sumNum))
sortArr = np.sort(arr)
print(sortArr)
posNum = 0
negNum = 0
for j in arr :
  if j>=0 :posNum=posNum + 1
  else :negNum = negNum + 1

print("posNum=" + str(posNum))
print("negNum=" + str(negNum))


n=3
number =1
number =4
number =-3
[1, 4, -3]
max = 4
min = -3
sum = 2
[-3  1  4]
posNum=2
negNum=1


Task 1.2. Develop a Python program to compute Sn as follows:
𝑆𝑛 = 1 + 1/3 + 1/5 + ⋯ + 1/2𝑛 + 1

In [30]:

sum = 0
n = int(input("n=")) 
for i in range(n):
    sum += 1/(2*i+1)

print("sum=" + str(sum))

n=10
sum=2.1332555301595546


Task 1.3. For a given class diagram as follows:


In [32]:
class Product:
    def __init__(self, name, type, price, expiredDate):
        self.__name = name
        self.__type = type
        self.__price = price
        self.__expiredDate = expiredDate

    def __str__(self):
        return self.__name + " " + self.__type + " " + str(self.__price) + " " + self.__expiredDate

    def get_price(self):
        return self.__price

class OrderItem:
    def __init__(self, product, amount):
        self.product = product
        self.amount = amount

    def get_product(self):
        return self.product

    def __str__(self):
        return self.product.__str__() + " " + str(self.amount)

class Order:
    def __init__(self, id, customer, employee, date, orderItem = []):
        self.id = id
        self.customer = customer
        self.employee = employee
        self.date = date
        self.orderItem = orderItem

    def get_orderItem(self):
        return self.orderItem

    def __str__(self):
        return format(self.id) + " " + self.customer + " " + self.employee + " " + self.date + " " + self.orderItem.__str__()

class OrderManger:
    def __init__(self, listOrder = []):
        self.listOrder = listOrder

    def highestPriceProduct(self):
        highestPrice = 0
        for i in self.listOrder:
            for j in i:
                if j.product.price > highestPrice:
                    highestPrice = j.product.price
        return highestPrice

    def showNumOfProBoughtByEachType(self):
        results = {
            "numberOfPro": 0,
            "typeOfPro": ""
        }
        for i in self.listOrder:
            for j in i:
                results.pop(1, j.product.type)
        return results

    def __str__(self):
        return self.listOrder.__str__()

p1 = Product("giường", "phòng ngủ", 200000, "1-2-2023")
p2 = Product("bàn ăn", "phòng ăn", 100000, "1-3-2023")
p3 = Product("ghế sofa", "phòng khách", 250000, "1-5-2025")

listOrderItem = []
orderItem1 = OrderItem(p1, 2)
orderItem2 = OrderItem(p2, 2)
orderItem3 = OrderItem(p3, 5)

listOrderItem.append(orderItem1)
listOrderItem.append(orderItem2)
listOrderItem.append(orderItem3)

order1 = Order(1, "nguyen van a", "hoang thi b", "20-1-2024", listOrderItem)

listOrder = [order1]
orderManger = OrderManger(listOrder)
print(str(orderManger.highestPriceProduct))

<bound method OrderManger.highestPriceProduct of <__main__.OrderManger object at 0x7f1a2e67beb0>>


Task 2.1 Develop a NumPy program to create an array with values ranging from 10 to 25, 
then reverse the array (the first element becomes last)

In [35]:
arr = np.arange(10, 26, 1)
print("arr=" , arr)
print("reverse arr =" , np.flip(arr))

arr= [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
reverse arr = [25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Task 2.2. Develop a NumPy program that constructs an array by repeating.

In [41]:
arr = [1,2,3,4]
print("arr=" , np.tile(arr,2))

arr= [1 2 3 4 1 2 3 4]


Task 2.3. Develop a NumPy program to replace all elements of NumPy array that are greater 
than a specified array.

In [43]:
arr1 = [(0.42, 0.48, 0.32)]
arr2 = [(0.74, 0.58, 0.38)]
arr3 = [(0.51, 0.34, 0.15)]
arr = np.array([arr1, arr2, arr3])
print(np.matrix(arr), '\n')

arr[(arr > .5)] = .5
print(np.matrix(arr))

[[0.42 0.48 0.32]
 [0.74 0.58 0.38]
 [0.51 0.34 0.15]] 

[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
